# Generated by Django 3.2.15 on 2022-08-13 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('NID', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('current', 'CURRENT'), ('on_leave', 'ON_LEAVE'), ('left', 'LEFT')], default='current', max_length=10)),
                ('designation', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 23, 27, 16, 336076)),
        ),
    ]
