# Generated by Django 3.2.15 on 2022-08-13 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220814_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hired_date',
            field=models.DateField(default='2022-08-14'),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 0, 6, 29, 677101)),
        ),
    ]
