# Generated by Django 3.2.15 on 2022-08-17 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20220815_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='current_month',
            field=models.DateField(default='2022-08-17'),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 21, 17, 58, 827248)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hired_date',
            field=models.DateField(default='2022-08-17'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='current_month',
            field=models.DateField(default='2022-08-17'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 21, 17, 58, 826275)),
        ),
        migrations.CreateModel(
            name='DonorAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('date_time_logged', models.DateTimeField(default=datetime.datetime(2022, 8, 17, 21, 17, 58, 827248))),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.donor')),
            ],
        ),
    ]
