# Generated by Django 3.2.15 on 2022-08-22 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20220817_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('zakat', 'ZAKAT'), ('donation', 'DONATION'), ('instituitions', 'INSTITUITIONS'), ('miscellaneous', 'MISCELLANEOUS')], default='donation', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='donoramount',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donoramount',
            name='date',
            field=models.DateField(default='2022-08-22'),
        ),
        migrations.AlterField(
            model_name='donoramount',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 12, 22, 213402)),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='current_month',
            field=models.DateField(default='2022-08-22'),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 12, 22, 213402)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hired_date',
            field=models.DateField(default='2022-08-22'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='current_month',
            field=models.DateField(default='2022-08-22'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 12, 22, 212425)),
        ),
    ]
