# Generated by Django 3.2.15 on 2022-08-13 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentfees_date_time_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='current_month',
            field=models.DateField(default='2022-08-14'),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 0, 3, 12, 969492)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(max_length=150),
        ),
    ]
