# Generated by Django 3.2.15 on 2022-08-13 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20220814_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='date_time_logged',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 1, 45, 45, 761382)),
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.DateField(default='2022-08-14')),
                ('total_salary', models.IntegerField(default=2000)),
                ('bonus_amount', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('left_amount', models.PositiveIntegerField(default=2000)),
                ('date_time_logged', models.DateTimeField(default=datetime.datetime(2022, 8, 14, 1, 45, 45, 760406))),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher')),
            ],
        ),
    ]
